LIB = lib/
COMPILER = g++ -c
LINKER = g++ 
DEBUGFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -g -Og -DSAFE_MODE -fPIC
DEVELFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -fPIC
OPTFLAGS =  -ansi -Wall -Wextra -pedantic -malign-double -O3 -DNDEBUG -fPIC -march=native -ffast-math
LINKSFLAGS = -lpthread
DEBUGDIR = debug/
OPTDIR = opt/
DEVELDIR = devel/
